server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://localhost:8080/realms/oauth2
          jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
          jws-algorithms:
#            - HS256 # 대칭키 알고리즘
            - RS256 # 비대칭키 알고리즘